#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
icon: http://www.ericsson.com/microservices_chassis_logo.png
name: eric-oss-data-loader
type: application
version: 1.0.27-84
