#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if (index .Values "eric-oss-performance-monitoring-enabler-pg" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-oss-performance-monitoring-enabler.pgSecretName" . }}
  labels:
  {{- include "eric-oss-performance-monitoring-enabler.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-performance-monitoring-enabler.annotations" . | nindent 4 }}
type: Opaque
data:
  {{/* retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result */}}
  {{- $secretName := print (include "eric-oss-performance-monitoring-enabler.pgSecretName" .) -}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
  {{- $secretData := (get $secretObj "data") | default dict -}}
  {{/* set field to existing secret data or generate a random values when secret does not exist */}}
  {{ $dbConfig := index .Values "eric-oss-performance-monitoring-enabler-pg" }}
  custom-user: {{ (get $secretData "custom-user") | default ($dbConfig.postgresUser | default (randAlphaNum 10) | b64enc) | quote }}
  custom-pwd: {{ (get $secretData "custom-pwd") | default ($dbConfig.postgresPassword | default (randAlphaNum 10) | b64enc) | quote }}
  super-user: {{ (get $secretData "super-user") | default ($dbConfig.postgresSuperUser | default (randAlphaNum 10) | b64enc) | quote }}
  super-pwd: {{ (get $secretData "super-pwd") | default ($dbConfig.postgresSuperPassword | default (randAlphaNum 10) | b64enc) | quote }}
  metrics-user: {{ (get $secretData "metrics-user") | default ($dbConfig.metricsUser | default (randAlphaNum 10) | b64enc) | quote }}
  metrics-pwd: {{ (get $secretData "metrics-pwd") | default ($dbConfig.metricsPwd | default (randAlphaNum 10) | b64enc) | quote }}
  replica-user: {{ (get $secretData "replica-user") | default ($dbConfig.replicaUser | default (randAlphaNum 10) | b64enc) | quote }}
  replica-pwd: {{ (get $secretData "replica-pwd") | default ($dbConfig.replicaPwd | default (randAlphaNum 10) | b64enc) | quote }}
{{ end }}