DROP table configurations;

create table kpi_configurations (
    id bigint generated by default as identity primary key,
    kpi_name varchar(255) NOT NULL,
    monitor boolean NOT NULL,
    threshold_type varchar(8) NOT NULL,
    fixed_threshold_value float,
    relevance_threshold float,
    confidence_interval float,
    session_configuration_id bigint
);

create table session_configurations (
    id bigint generated by default as identity primary key,
    name varchar(255) UNIQUE NOT NULL,
    number_of_connected_users_for_reliability int NOT NULL,
    weekend_days varchar(255) NOT NULL
);