#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: rAppId
  labels:
    strimzi.io/cluster: eric-oss-dmm-kf-op-sz
spec:
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: epme-monitoring-objects
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: epme-verdicts
          patternType: literal
        operation: Write
      - resource:
          name: '*'
          patternType: literal
          type: group
        operation: All