#
# COPYRIGHT Ericsson 2023 - 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: 2.0
zapConfig:
  baseUrl: "http://eric-oss-performance-monitoring-enabler:8080"
  scanType: "full"
  config_dir: "generated/configs/zap-config"
  globalConfig:
    - id: "100001"
      action: "IGNORE"
      message: "Unexpected Content-Type was returned"
    - id: "100000"
      action: "IGNORE"
      message: "A Server Error response code was returned by the server"
    - id: "10021"
      action: "IGNORE"
      message: "X-Content-Type-Options Header Missing"
    - id: "40042"
      action: "IGNORE"
      message: "Spring Actuator Information Leak"
  endpoints:
    - name: "sessions"
      url: "/v1alpha3/sessions?clientId=rappid--1--261854e7-2b26-4dc7-8d68-5bf01cfe62b4"
    - name: "configurations"
      url: "/v1alpha3/configurations"
  report:
    dir: "build/va-reports/zap-reports"
    format:
      - html
      - json
      - md
      - xml
  properties:
    zap_container_port: 9625