#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if eq .Values.kafka.tls.enabled true }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ template "eric-oss-performance-monitoring-enabler-testware.name" . }}
  labels:
    strimzi.io/cluster: eric-oss-dmm-kf-op-sz
    {{- include "eric-oss-performance-monitoring-enabler-testware.labels" . | nindent 4 }}
spec:
  authentication:
    type: tls-external
  authorization:
    type: simple
    acls:
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
      - operation: Write
        resource:
          name: 'epme-monitoring-objects'
          patternType: literal
          type: topic
      - operation: Read
        resource:
          name: 'epme-verdicts'
          patternType: literal
          type: topic
{{- end }}